// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/callback.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/logout.tsx";
import * as $7 from "./routes/secured/_middleware.ts";
import * as $8 from "./routes/secured/index.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/callback.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/logout.tsx": $6,
    "./routes/secured/_middleware.ts": $7,
    "./routes/secured/index.tsx": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
